---
# This file contains configuration for the LGTM.com static code analysis tool.
# The python-blosc GitHub repository is continuously scanned by the LGTM.com
# tool for security and/or code vulnerabilities. You can find the alerts here:
# https://lgtm.com/projects/g/Blosc/python-blosc/

path_classifiers:
  generated:
    # suppress alerts in vendored files
    - cpuinfo.py
    - blosc/_version.py
    - blosc/c-blosc
