# AppVeyor CI build configuration for c-blosc

# Before cloning the repo, configure git to handle line endings correctly.
init:
  - git config --global core.autocrlf input

# This is the build version displayed on AppVeyor's UI.
# It's incrementally automatically like travis-ci but allows custom formatting.
version: '{build}'

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  matrix:
    # Unfortunately, I was not able to correctly make VS2008 to work
    # - GENERATOR: "Visual Studio 9 2008"
    #   CONFIG: Release

    # Using Win64 for 2008 is unnecessarily complicated.  See:
    # http://help.appveyor.com/discussions/kb/38-visual-studio-2008-64-bit-builds
    # - GENERATOR: "Visual Studio 9 2008 Win64"
    #   CONFIG: Release

    - GENERATOR: "Visual Studio 10 2010"
      CONFIG: Release

    - GENERATOR: "Visual Studio 10 2010 Win64"
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 2013"
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 Win64"
      CONFIG: Release

build_script:
  - cmake "-G%GENERATOR%" -H. -B_builds
  - cmake --build _builds --config "%CONFIG%"

test_script:
  - ps: cd _builds
  - ctest -VV -C "%CONFIG%"
